//
//  CachedRepositoryListModuleViewController.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 05.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by
//

import UIKit

class CachedRepositoryListModuleViewController: UIViewController {
    
    //MARK: - @IBOutlets
    @IBOutlet weak var tableView: UITableView!
    
    
    //MARK: - Properties
	var output: CachedRepositoryListModuleViewOutput?
    var displayManager = CachedRepositoryListDataDisplayManager()

    //MARK: - Life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        
        output?.didLoadView()
        displayManager.configureFor(tableView: tableView, baseDelegate: self)
    }
}

extension CachedRepositoryListModuleViewController: CachedRepositoryListModuleViewInput {
    
    func updateDataSource(repositories: [Repository]) {
        displayManager.updateTableWith(repositories: repositories)
    }
    
    func configureNavigationTitle(text: String) {
        title = text
    }
}

extension CachedRepositoryListModuleViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        output?.didSelectRowAt(index: indexPath)
    }
}

