//
//  RepositorySearchModulePresenter.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 04.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by 
//

import UIKit

class RepositorySearchModulePresenter: RepositorySearchModuleInput {

    //MARK: - Properties
    weak private var view: RepositorySearchModuleViewInput?
    var interactor: RepositorySearchModuleInteractorInput?
    private let router: RepositorySearchModuleRouterInput

    
    init(interface: RepositorySearchModuleViewInput, interactor: RepositorySearchModuleInteractorInput?, router: RepositorySearchModuleRouterInput) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension RepositorySearchModulePresenter: RepositorySearchModuleViewOutput {
    
    func showError(text: String) {
        view?.showOkAlert(title: "Error", text: text)
    }
    
    func openRepositoryListModule(searchText: String) {
        router.openRepositoryListModule(searchText: searchText)
    }
}

extension RepositorySearchModulePresenter: RepositorySearchModuleInteractorOutput {
    
    func didTapSearch(text: String?) {
        interactor?.validate(searchText: text)
    }
    
    func didTapShowHistory() {
        router.openCachedRepositoryListModule()
    }
}
