//
//  RepositoryListModuleRouter.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 04.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by 
//

import UIKit

class RepositoryListModuleRouter {
    
    //MARK: - Properties
    weak var view: UIViewController?
}

extension RepositoryListModuleRouter: RepositoryListModuleRouterInput {
    
    func openRepositoryDetail(url: URL, repositoryId: Int32?) {
        let stateStorage = RepositoryDetailModulePresenterStateStorage(url: url, repositoryId: repositoryId)
        let repositoryDetailModuleView = RepositoryDetailModuleAssembly(presenterStateStorage: stateStorage, presenter: nil).view
        
        repositoryDetailModuleView.modalTransitionStyle = .crossDissolve
        repositoryDetailModuleView.modalPresentationStyle = .overCurrentContext
        view?.present(repositoryDetailModuleView, animated: true, completion: nil)
    }
}
