//
//  RepositoryDetailModuleAssembly.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 03.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by Stanislav Kaliberov
//

import UIKit

final class RepositoryDetailModuleAssembly {
    
    var stateStorage: RepositoryDetailModuleStateStorage
    
    init(stateStorage: RepositoryDetailModuleStateStorage) {
        self.stateStorage = stateStorage
    }
    
    var view: UIViewController {
        guard let viewController = UIStoryboard(name: "RepositoryDetailModule", bundle: nil).instantiateInitialViewController() as? RepositoryDetailModuleViewController else {
            assert(false, "\(self) should be defined")
        }
        
        self.configureModule(view: viewController)
        return viewController
    }
    
    private func configureModule(view: RepositoryDetailModuleViewController) {
        let router = RepositoryDetailModuleRouter()
        let interactor = RepositoryDetailModuleInteractor()
        let presenter = RepositoryDetailModulePresenter(interface: view, interactor: interactor, router: router, stateStorage: stateStorage)
        
        router.view = view
        interactor.presenter = presenter
        presenter.interactor = interactor
        view.presenter = presenter
    }
}
