//
//  RepositoryDetailModulePresenter.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 03.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by 
//

import UIKit

class RepositoryDetailModulePresenter {

    //MARK: - Properties
    weak private var view: RepositoryDetailModuleViewInput?
    var interactor: RepositoryDetailModuleInteractorInput?
    private let router: RepositoryDetailModuleRouterInput
    
    var stateStorage: RepositoryDetailModuleStateStorage
    
    init(interface: RepositoryDetailModuleViewInput, interactor: RepositoryDetailModuleInteractorInput?, router: RepositoryDetailModuleRouterInput,  stateStorage: RepositoryDetailModuleStateStorage) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.stateStorage = stateStorage
    }
}

extension RepositoryDetailModulePresenter: RepositoryDetailModuleViewOutput {
}

extension RepositoryDetailModulePresenter: RepositoryDetailModulePresenterInput {
    
    func didLoadView() {
        view?.openPage(with: stateStorage.url)
    }
    
    func didTapCloseButton() {
        router.dissmis(with: true)
    }
    
    func didGesturePerform(sender: UITapGestureRecognizer) {
        router.dissmis(with: true)
    }
}

extension RepositoryDetailModulePresenter: RepositoryDetailModulePresenterOutput {
    
    
}
