//
//  RepositoryDetailModuleDataDisplayManager.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 03.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by
//

import UIKit

class RepositoryDetailModuleDataDisplayManagerDataDisplayManager {
    
}
