//
//  RepositoryDetailModuleProtocols.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 03.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by Stanislav Kaliberov
//

import UIKit

//MARK: Router -
protocol RepositoryDetailModuleRouterInput: class {
    func dissmis(with animation: Bool)
}

//MARK: View -

protocol RepositoryDetailModuleViewInput: class {
    func openPage(with url: URL)
}

protocol RepositoryDetailModuleViewOutput: class {
//    func viewDidPressOnCloseButton()
}


//MARK: Presenter -

protocol RepositoryDetailModulePresenterInput: class {
    func didLoadView()
    func didTapCloseButton()
    func didGesturePerform(sender: UITapGestureRecognizer)
}

protocol RepositoryDetailModulePresenterOutput: class {
    
}


//MARK: Interactor -
protocol RepositoryDetailModuleInteractorInput: class {
    
}



