//
//  RepositoryDetailModuleInteractor.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 03.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by Stanislav Kaliberov
//

import UIKit

class RepositoryDetailModuleInteractor {

    //MARK: - Properties
    weak var presenter: RepositoryDetailModulePresenterOutput?
}

extension RepositoryDetailModuleInteractor: RepositoryDetailModuleInteractorInput {
    
}
