//
//  RepositorySearchModuleRouter.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 04.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by 
//

import UIKit

class RepositorySearchModuleRouter {
    
    //MARK: - Properties
    weak var view: UIViewController?
}

extension RepositorySearchModuleRouter: RepositorySearchModuleRouterInput {
    
    func openCachedRepositoryListModule() {
        let cachedRepositoryListView = CachedRepositoryListModuleAssembly().view
        view?.navigationController?.navigationBar.prefersLargeTitles = true
        view?.navigationController?.pushViewController(cachedRepositoryListView, animated: true)
    }
    
    func openRepositoryListModule(searchText: String) {
        let repositoryListView = RepositoryListModuleAssembly(presenterStateStorage: RepositoryListModulePresenterStateStorage(searchText: searchText)).view
        view?.navigationController?.pushViewController(repositoryListView, animated: true)
    }
}
