//
//  RepositorySearchModuleAssembly.swift
//  GitBrowser
//
//  Created Станислав Калиберов on 04.12.2017.
//  Copyright © 2017 Станислав Калиберов. All rights reserved.
//
//  Template generated by Stanislav Kaliberov
//

import UIKit

final class RepositorySearchModuleAssembly {
    
    var view: UIViewController {
        guard let viewController = UIStoryboard(name: ModulesConstant.Storyboard.repositorySearch.rawValue, bundle: nil).instantiateInitialViewController() as? RepositorySearchModuleViewController else {
            assert(false, "\(self) should be defined")
        }
        
        self.configureModule(view: viewController)
        return viewController
    }
    
    private func configureModule(view: RepositorySearchModuleViewController) {
        let router = RepositorySearchModuleRouter()
        let interactor = RepositorySearchModuleInteractor()
        let presenter = RepositorySearchModulePresenter(interface: view, interactor: interactor, router: router)
        
        router.view = view
        presenter.interactor = interactor
        interactor.output = presenter
        view.output = presenter
    }
}
